apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore # Bad practice, but I'm alone
metadata:
  name: gitlab-secret-store
spec:
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            name: gitlab-token
            key: token
            namespace: external-secret
      projectID: "62522045"
