apiVersion: v1
kind: PersistentVolume
metadata:
  name: download-pv
  labels:
    name: download
spec:
  storageClassName: standard
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4
  nfs:
    path: /volume1/qbittorrentdownload
    server: nas.sarapuce.fr
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: download-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  selector:
    matchLabels:
      name: download
