apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy
    creationPolicy: Owner
  data:
  - secretKey: client-id
    remoteRef:
      key: oauth2_client_id
  - secretKey: client-secret
    remoteRef:
      key: oauth2_client_secret
  - secretKey: cookie-secret
    remoteRef:
      key: oauth2_cookie_secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-accesslist
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-accesslist
    creationPolicy: Owner
  data:
  - secretKey: restricted_user_access
    remoteRef:
      key: oauth2_proxy_accesslist
