apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repository-credentials
  labels:
    argocd.argoproj.io/secret-type: repo-creds
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-repository-credentials
    creationPolicy: Owner
  data:
  - secretKey: sshPrivateKey
    remoteRef:
      key: ssh_argo_key
  - secretKey: url
    remoteRef:
      key: argo_repo_url
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-webhook-secret
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-secret-webhook
    creationPolicy: Owner
  data:
  - secretKey: webhook.github.secret
    remoteRef:
      key: argocd_webhook
