# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: prowlarr-config-pv
#   labels:
#     name: prowlarr-config
# spec:
#   storageClassName: longhorn
#   capacity:
#     storage: 200Mi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/var/prowlarr/config"
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  # selector:
  #   matchLabels:
  #     name: prowlarr-config
