apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: git@github.com:sarapuce/argocd-homelab
      revision: HEAD
      directories:
        - path: apps/*/*
        # - path: apps/all-namespaces/*
        #   exclude: true
  template:
    metadata:
      name: "{{.path.basename}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: git@github.com:sarapuce/argocd-homelab
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        name: in-cluster
        namespace: "{{index .path.segments 1}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
