apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: all-namespaces
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project used for all-namespaces applications
  sourceRepos:
  - '*'
  destinations:
  - server: https://kubernetes.default.svc
    name: in-cluster
    namespace: '*'
