apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: exatorrent
  name: exatorrent
  namespace: exatorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exatorrent
  template:
    metadata:
      labels:
        app: exatorrent
    spec:
      containers:
        - image: ghcr.io/varbhat/exatorrent:1.3.0
          name: exatorrent
          env:
            - name: EXAPASSWORD
              valueFrom:
                secretKeyRef:
                  name: exatorrent-creds
                  key: password
            - name: EXAUSERNAME
              valueFrom:
                secretKeyRef:
                  name: exatorrent-creds
                  key: username
          args:
            - "-admin"
            - "$(EXAUSERNAME)"
            - "-passw"
            - "-dir"
            - "exadir"
          ports:
            - containerPort: 5000
              name: http
            - containerPort: 42069
              name: torrent
          volumeMounts:
            - mountPath: /exa/exadir
              name: config-volume
      volumes:
        - emptyDir:
            sizeLimit: 500Mi
          name: config-volume
