apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate
spec:
  secretName: tls-secret
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt-dns
  commonName: "*.sarapuce.fr"
  dnsNames:
    - "*.sarapuce.fr"
