oauth2-proxy:
  ingress:
    enabled: true
    hosts:
      - oauth2.sarapuce.fr
    pathType: ImplementationSpecific
    className: public
  config:    
    configFile: |-
      redirect_url="/oauth2/callback"
      whitelist_domains="*.sarapuce.fr"
      cookie_domains=".sarapuce.fr"
      cookie_expire="48h"
      cookie_secure="false"
      provider="google"
      reverse_proxy="true"
      cookie_refresh="1h"
      skip_auth_preflight="true"
    existingSecret: oauth2-proxy

  authenticatedEmailsFile:
    enabled: true
    persistence: secret
