---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    name: in-cluster
  source:
    repoURL: git@github.com:sarapuce/argocd-homelab
    targetRevision: HEAD
    path: application-set
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
