apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  namespace: hello-world
spec:
  ingressClassName: public
  rules:
  - host: hello.sarapuce.fr
    http:
      paths:
      - backend:
          service:
            name: {{ include "helloworld.fullname" . }}
            port:
              number: 5678
        path: /
        pathType: Prefix
