apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-pv
  labels:
    name: sonarr-config
spec:
  storageClassName: standard
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4
  nfs:
    path: /volume1/sonarrconfig
    server: nas.sarapuce.fr
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      name: sonarr-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-tv-pv
  labels:
    name: sonarr-tv
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4
  nfs:
    path: /volume1/sonarrtv
    server: nas.sarapuce.fr
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-tv-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: sonarr-tv
