apiVersion: v1
kind: Service
metadata:
  name: deluge-service
spec:
  selector:
    app: deluge
  ports:
    - name: web
      protocol: TCP
      port: 8112
      targetPort: web
    - name: torrent-tcp
      protocol: TCP
      port: 6881
      targetPort: torrent-tcp
    - name: torrent-udp
      protocol: UDP
      port: 6881
      targetPort: torrent-udp
    - name: thin-client
      protocol: TCP
      port: 58846
      targetPort: thin-client
  type: ClusterIP
