apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ovh-credentials
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore
  target:
    name: ovh-credentials
    creationPolicy: Owner
  data:
  - secretKey: applicationKey
    remoteRef:
      key: ovh_application_key
  - secretKey: applicationSecret
    remoteRef:
      key: ovh_application_secret
  - secretKey: consumerKey
    remoteRef:
      key: ovh_consumer_key

