apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: argocd-repository-credentials
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-repository-credentials
    creationPolicy: Owner
  data:
  - secretKey: sshPrivateKey
    remoteRef:
      key: ssh_argo_key
  - secretKey: url
    remoteRef:
      key: argo_repo_url

